# Generated by Django 3.1 on 2020-08-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataconsulta',
            fields=[
                ('id_dataconsulta', models.AutoField(db_column='ID_DATAcONSULTA', primary_key=True, serialize=False)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'DATAcONSULTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id_hashtag', models.AutoField(db_column='ID_HASHTAG', primary_key=True, serialize=False)),
                ('hashtag', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'HASHTAG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sentimiento',
            fields=[
                ('id_sentimiento', models.AutoField(db_column='ID_SENTIMIENTO', primary_key=True, serialize=False)),
                ('sentimiento', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'SENTIMIENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id_tweet', models.AutoField(db_column='ID_TWEET', primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('numlikes', models.IntegerField(blank=True, db_column='numLikes', null=True)),
                ('numcitado', models.IntegerField(blank=True, db_column='numCitado', null=True)),
                ('numretweet', models.IntegerField(blank=True, db_column='numRetweet', null=True)),
                ('numrespuesta', models.IntegerField(blank=True, db_column='numRespuesta', null=True)),
                ('texto', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TWEET',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TweetHashtag',
            fields=[
                ('id_tweet_hashtag', models.AutoField(db_column='ID_TWEET_HASHTAG', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TWEET_HASHTAG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('numseguidor', models.IntegerField(blank=True, db_column='numSeguidor', null=True)),
                ('numtweet', models.IntegerField(blank=True, db_column='numTweet', null=True)),
                ('imgusuario', models.CharField(blank=True, db_column='imgUsuario', max_length=400, null=True)),
                ('verificado', models.BooleanField(blank=True, null=True)),
                ('urlusuario', models.CharField(blank=True, db_column='urlUsuario', max_length=300, null=True)),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': False,
            },
        ),
    ]
